Fix printf-builderror; Remove printf() from non-rootservers
- Fix "undefined reference to printf" build error - the order of libs given to the "ld" command was wrong.
- Remove all printf from the servers (except from the rootserver) - caused weird problems: the logserver-calls weren't completely printed